# frozen_string_literal: true

require 'test_helper'

# Gated EXPLAIN query plan tests for ClickHouse analytics services.
#
# These tests capture the actual SQL generated by analytics service methods,
# run EXPLAIN indexes=1 on each captured query, and verify that critical
# filters (project_id, date range) appear in the query plan. This catches
# regressions where a refactor accidentally drops a partition/PK filter,
# causing full table scans in production.
#
# Double-gated:
#   1. skip_unless_clickhouse! -- requires a running CH instance
#   2. ENV['CH_PERF_TESTS']   -- opt-in (EXPLAIN output format varies by CH version)
#
# Run: CH_PERF_TESTS=1 bundle exec rails test test/services/analytics/query_plan_test.rb
class Analytics::QueryPlanTest < ActiveSupport::TestCase
  include ClickhouseTestHelper
  include GoldenDatasetHelper

  fixtures :projects, :instances

  setup do
    skip 'EXPLAIN tests gated behind CH_PERF_TESTS env var' unless ENV['CH_PERF_TESTS']
    skip_unless_clickhouse!
    setup_golden_dataset
    @project = golden_project
  end

  teardown { teardown_golden_dataset }

  # ---------------------------------------------------------------------------
  # 1. EventsQueryService.list SQL includes project_id filter
  # ---------------------------------------------------------------------------
  # The events table ORDER BY starts with project_id, so EXPLAIN should show
  # it as a key condition. If project_id is missing from WHERE, ClickHouse
  # would scan all projects -- a catastrophic performance bug.
  test 'events list query includes project_id filter in EXPLAIN output' do
    sqls = capture_ch_read_sql do
      Analytics::EventsQueryService.list(
        @project.id,
        start_date: golden_start_date,
        end_date:   golden_end_date,
        include_count: false
      )
    end

    assert sqls.any?, 'Expected at least 1 captured SQL from EventsQueryService.list'

    sqls.each do |sql|
      plan = explain_query(sql)
      assert_match(/project_id/, plan,
                   "EXPLAIN output for events list query should reference project_id.\n" \
                   "Captured SQL: #{sql}\nEXPLAIN output:\n#{plan}")
    end
  end

  # ---------------------------------------------------------------------------
  # 2. EventsQueryService.list SQL includes date range filter
  # ---------------------------------------------------------------------------
  # The events table ORDER BY includes toDate(created_at) as the second key
  # component, and is PARTITION BY toYYYYMM(created_at). The date range
  # filter should appear in the EXPLAIN output as a partition or key condition.
  test 'events list query includes date filter in EXPLAIN output' do
    sqls = capture_ch_read_sql do
      Analytics::EventsQueryService.list(
        @project.id,
        start_date: golden_start_date,
        end_date:   golden_end_date,
        include_count: false
      )
    end

    assert sqls.any?, 'Expected at least 1 captured SQL from EventsQueryService.list'

    sqls.each do |sql|
      plan = explain_query(sql)
      # The date filter uses toDate(created_at) which should appear in
      # key conditions or partition pruning info.
      has_date_ref = plan.include?('created_at') || plan.include?('event_date')
      assert has_date_ref,
             "EXPLAIN output for events list query should reference date filter.\n" \
             "Captured SQL: #{sql}\nEXPLAIN output:\n#{plan}"
    end
  end

  # ---------------------------------------------------------------------------
  # 4. No critical service query is missing project_id in WHERE clause
  # ---------------------------------------------------------------------------
  # Runs all major analytics service methods, captures every SQL statement,
  # and asserts that every SELECT FROM a data table includes project_id
  # somewhere in the query text. This is a belt-and-suspenders check --
  # even if EXPLAIN parsing is fragile across CH versions, raw SQL text
  # inspection is reliable.
  test 'no query across all major services is missing project_id' do
    all_sqls = []

    # EventsQueryService
    all_sqls.concat(capture_ch_read_sql do
      Analytics::EventsQueryService.list(
        @project.id, start_date: golden_start_date, end_date: golden_end_date
      )
    end)

    all_sqls.concat(capture_ch_read_sql do
      Analytics::EventsQueryService.volume(
        @project.id, start_date: golden_start_date, end_date: golden_end_date, bucket: 'day'
      )
    end)

    all_sqls.concat(capture_ch_read_sql do
      Analytics::EventsQueryService.field_values(@project.id, field: 'platform')
    end)

    # RetentionService
    all_sqls.concat(capture_ch_read_sql do
      Analytics::RetentionService.summary(@project.id)
    end)

    # SessionsQueryService
    all_sqls.concat(capture_ch_read_sql do
      Analytics::SessionsQueryService.list(
        @project.id, start_date: golden_start_date, end_date: golden_end_date
      )
    end)

    # OverviewStatsService
    all_sqls.concat(capture_ch_read_sql do
      Analytics::OverviewStatsService.versions(
        @project.id, start_date: golden_start_date, end_date: golden_end_date
      )
    end)

    all_sqls.concat(capture_ch_read_sql do
      Analytics::OverviewStatsService.sources_breakdown(
        @project.id, start_date: golden_start_date, end_date: golden_end_date
      )
    end)

    assert all_sqls.any?, 'Expected to capture at least one SQL statement across all services'

    missing_project_id = all_sqls.reject { |sql| sql.include?('project_id') }
    assert_empty missing_project_id,
                 "Found #{missing_project_id.size} query(ies) without project_id:\n" \
                 "#{missing_project_id.map { |s| s.lines.first(3).join }.join("\n---\n")}"
  end

  # ---------------------------------------------------------------------------
  # 5. EXPLAIN confirms no full table scan (ReadFromMergeTree without key
  #    conditions) on any critical query
  # ---------------------------------------------------------------------------
  # A full scan without project_id key filtering would show up in EXPLAIN
  # as ReadFromMergeTree with no Keys listed, or with "Parts: all" and no
  # granule filtering. We check that at least some granule/part pruning
  # occurs for each query.
  test 'explained queries show key filtering, not unfiltered full scans' do
    representative_sqls = []

    representative_sqls.concat(capture_ch_read_sql do
      Analytics::EventsQueryService.list(
        @project.id, start_date: golden_start_date, end_date: golden_end_date
      )
    end)

    representative_sqls.concat(capture_ch_read_sql do
      Analytics::SessionsQueryService.list(
        @project.id, start_date: golden_start_date, end_date: golden_end_date
      )
    end)

    representative_sqls.concat(capture_ch_read_sql do
      Analytics::RetentionService.summary(@project.id)
    end)

    assert representative_sqls.any?, 'Expected at least one SQL to EXPLAIN'

    representative_sqls.each do |sql|
      plan = explain_query(sql)

      # EXPLAIN indexes=1 output for MergeTree includes "Keys:" lines when
      # the primary key is used for filtering. If there are no Keys lines at
      # all, it means no key-based filtering is happening.
      #
      # However, on small test datasets ClickHouse might skip reporting key
      # conditions because the data fits in a single granule. So we check
      # for the presence of project_id in the SQL itself as a fallback --
      # the important thing is the WHERE clause exists.
      has_key_filtering = plan.include?('Key') || plan.include?('Condition')
      has_project_in_sql = sql.include?('project_id')

      assert has_key_filtering || has_project_in_sql,
             "Query appears to lack key filtering and project_id WHERE clause.\n" \
             "SQL: #{sql.lines.first(5).join}\nEXPLAIN:\n#{plan}"
    end
  end

  private

  # ---------------------------------------------------------------------------
  # SQL Capture Helper
  # ---------------------------------------------------------------------------
  # Captures every query sent to ClickHouse via ActiveSupport::Notifications.
  # Returns an array of CapturedQuery structs preserving both the SQL text
  # and any parameterized placeholders so EXPLAIN can replay them correctly.
  CapturedQuery = Struct.new(:sql, :placeholders, keyword_init: true) do
    def include?(str)
      sql.include?(str)
    end

    def lines
      sql.lines
    end

    def to_s
      sql
    end
  end

  def capture_ch_read_sql
    captured = []

    subscription = ActiveSupport::Notifications.subscribe('sql.click_house') do |_name, _start, _finish, _id, payload|
      q = payload[:query]
      next unless q

      if q.respond_to?(:to_sql) && q.respond_to?(:prepared_placeholders)
        captured << CapturedQuery.new(sql: q.to_sql, placeholders: q.prepared_placeholders)
      else
        captured << CapturedQuery.new(sql: q.to_s, placeholders: {})
      end
    end

    yield

    captured
  ensure
    ActiveSupport::Notifications.unsubscribe(subscription) if subscription
  end

  # ---------------------------------------------------------------------------
  # EXPLAIN Helper
  # ---------------------------------------------------------------------------
  # Runs EXPLAIN indexes=1 on a captured query. For parameterized queries,
  # wraps the EXPLAIN SQL in a ClickHouse::Client::Query with the original
  # placeholders so ClickHouse can substitute {name:Type} values server-side.
  def explain_query(captured)
    clean_sql = captured.sql.strip.chomp(';')
    explain_sql = "EXPLAIN indexes = 1 #{clean_sql}"

    if captured.placeholders.any?
      query = ClickHouse::Client::Query.new(
        raw_query: explain_sql,
        placeholders: captured.placeholders
      )
      rows = ClickHouse::Client.select(query, :main)
    else
      Clickhouse.with do |conn|
        rows = conn.select_all(explain_sql)
      end
    end

    rows.map { |r| r.values.first.to_s }.join("\n")
  rescue StandardError => e
    # If EXPLAIN fails (e.g., on a DDL or unsupported query), return
    # the error message so the test can still inspect it.
    "EXPLAIN_ERROR: #{e.class}: #{e.message}"
  end
end
